fix(FEC-11059): no replay button once ima postroll failed when midroll has skipped over
kaltura/playkit-js-ima pull request #191
Opened 2021-03-10 11:29 UTC by yairans

### Description of the Changes

The issue is only when the post-roll preloaded, so prevent post-roll preloading 

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-03-10 13:13 UTC, OrenMe submitted a review, later dismissed

2021-03-10 13:26 UTC, dan-ziv requested changes

2021-03-10 13:26 UTC, dan-ziv commented on src/ima.js
> +      adsRequest.contentDuration = -3;
why -3?

2021-03-10 15:49 UTC, dan-ziv commented on src/ima.js
> +      adsRequest.contentDuration = -3;
weirdos...
Anyway, set it to const so it will act as enum and be more understandable what's the meaning.
`const PRELOAD_NONE : number = -3;`

2021-03-11 12:05 UTC, dan-ziv approved these changes

2021-03-11 12:07 UTC, merged